; ICM on Scheme
; library.ss
; Author : Chill

(load "basic.ss")

(library (Number)
         (export is? f+ f- f* f/ =?)
         (import (rnrs))
         (define is? number?)
         (define f+ +)
         (define f- -)
         (define f* *)
         (define f/ /)
         (define =? =))

(library (String)
         (export is? f+ =? ->Symbol)
         (import (rnrs))
         (define is? string?)
         (define f+ string-append)
         (define =? string=?)
         (define ->Symbol string->symbol))

(library (Symbol)
         (export is? =? ->String)
         (import (rnrs))
         (define is? symbol?)
         (define =? symbol=?)
         (define ->String symbol->string))

(library (List)
         (export is? first second third)
         (import (rnrs))
         (define is? list?)
         (define (first lst)  (car lst))
         (define (second lst) (car (cdr lst)))
         (define (third lst)  (car (cdr (cdr lst)))))

(library (Vector)
         (export new is? size get set)
         (import (rnrs))
         (define new make-vector)
         (define is? vector?)
         (define size vector-length)
         (define get vector-ref)
         (define set vector-set!))

(library (HashTable)
         (export new is? insert get)
         (import (rnrs))
         (define new make-eq-hashtable)
         (define is? hashtable?)
         (define insert hashtable-set!)
         (define (get hashtable key) (hashtable-ref hashtable key `nil)))
